spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/teammanagerdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop    # ??????? ????? ??? ???????, ??????? ??? ?????????
    show-sql: true             # ??????? SQL-??????? ? ???
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true       # ??????????? SQL-??????? ??? ???????? ??????