spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/teammanagerdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  thymeleaf:
    cache: false
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true